apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeview.fullname" . }}
  labels:
{{ include "kubeview.labels" . | indent 4 }}
spec:
  {{ if .Values.ingress.enabled }}
  type: ClusterIP
  {{ else }}
  type: LoadBalancer
  {{ end }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubeview.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
{{- end }}
