name: kubeview
apiVersion: v2
version: 0.1.20
appVersion: '0.1.20'

description: Kubernetes cluster visualiser and visual explorer
maintainers:
  - name: Ben Coleman
    url: https://benc.dev

icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
home: https://github.com/benc-uk/kubeview
sources:
  - https://github.com/benc-uk/kubeview
