# Default values for kubeview.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Kubeview specific, if true the app will function in single namespace mode
# The roles & rolebindings created will be namespaced rather than cluster scoped
limitNamespace: false

replicaCount: 1

image:
  repository: ghcr.io/benc-uk/kubeview
  tag: 0.1.31
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# If you want to expose the kubeview service using an ingress
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
  tls: []
  className: ""

# If you want to expose the kubeview service directly
loadBalancer:
  IP: ""
  enabled: true

# Note.
# If both ingress and loadbalancer are disabled, a ClusterIP service will be created

# Mostly never need to change these
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
