name: Build Dockerhub Image

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
env:
  dockerUser: bencuk
  imageName: kubeview
  imageTag: latest
  
jobs:
  buildJob:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Check server code with gofmt
      run: bash .github/workflows/gofmt-action.sh cmd/server

    - name: Check UI code with ESLint
      run: npm install --silent && npm run lint
      working-directory: web/client

    - name: Build the Docker image
      run: docker build . --file ./build/Dockerfile --build-arg buildInfo="GitHub CI build $GITHUB_RUN_ID, of $GITHUB_REF on $(date -I)" --tag $dockerUser/$imageName:$imageTag
    
    - name: Login to Dockerhub
      if: github.repository == 'benc-uk/kubeview' && github.event_name == 'push'
      run: docker login -u $dockerUser -p ${{ secrets.dockerPassword }} 
      
    - name: Push to Dockerhub
      if: github.repository == 'benc-uk/kubeview' && github.event_name == 'push'
      run: docker push $dockerUser/$imageName:$imageTag
